### ISSUE TITLE
Meaning of RhspModuleStatus

### ISSUE THREAD

**Issue by polarbub** [REVrobotics/node-rhsplib#134]
I am wondering what the two members in [RhspModuleStatus](https://github.com/REVrobotics/node-rhsplib/blob/main/packages/rhsplib/librhsp/include/rhsp/module.h#L16) returned from [rhsp_getModuleStatus](https://github.com/REVrobotics/node-rhsplib/blob/main/packages/rhsplib/librhsp/src/rhsp.c#L38C5-L38C25) of librhsp mean. They seem to be bit flags, but I can't find any documentation about what each bit means. From a bit of experimentation bit 5 of `statusWord` seems to indicate whether there is a battery plugged in, but other than that the rest are a mystery.

**Comment by ItsHarper** [comment]
Here's where they're listed out in the FTC SDK: https://github.com/OpenFTC/Extracted-RC/blob/ce0a67af28c966c7a166ae51765e115a853734fc/Hardware/src/main/java/com/qualcomm/hardware/lynx/commands/standard/LynxGetModuleStatusResponse.java#L50
