### ISSUE TITLE
When the methods encounter an error, they should reject the returned Promise

### ISSUE THREAD

**Issue by NoahAndrews** [REVrobotics/node-rhsplib#16]
Returning an integer result code does not make for a natural-feeling JS API. The rejected promise should wrap a helpful [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) subclass with a helpful `message` passed in. For example, we could create a `SerialPortNotFoundError` class to be used when a non-existent serial port path is passed in.

**Comment by jfabellera** [comment]
I'm going to remove the `resultCode`, but for void functions I still need a value to resolve the promise on. I'm thinking of just returning a string of "OK". Is that the right way to go?

**Comment by NoahAndrews** [comment]
No, you should just return a `Promise<void`.

**Comment by NoahAndrews** [comment]
At least in Javascript, you can `resolve()` a promise without passing in a parameter. I assume the same thing should work for C++.

**Comment by jfabellera** [comment]
Napi requires an Napi::Value, and I can't find a `void` or `null` value

**Comment by NoahAndrews** [comment]
Pass in ` Env::Undefined()`

**Comment by NoahAndrews** [comment]
Actually that should be `Env().Undefined()`.
