### ISSUE TITLE
Throw custom `Error` sub-classes

### ISSUE THREAD

**Issue by NoahAndrews** [REVrobotics/node-rhsplib#23]
Unfortunately, we can't directly do this from C++, so we'll have to use a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy).

Rather than creating an error in the C++ code, we should call `Reject()` with a regular Javascript object containing the `errorCode` field (and the `nackCode` field, if applicable).

In `binding.ts`, rather than exporting `addon.Serial` and `addon.RevHub` directly, we should be exporting factory functions that instantiate the addon-defined classes, and bind a `Proxy` to the newly-instantiated object. That proxy can then use [handler.apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply) to intercept all function calls, catch our `errorCode`/`nackCode` JS object, and throw an appropriate custom `Error` subclass.

**Comment by NoahAndrews** [comment]
Oh, if we export `RevHub` and `Serial` as classes, it will still be possible to instantiate them directly, so those types need to be exported as `Interface`s (without the `constructor()` entries). `addon.Serial` and `addon.RevHub` should be typed as new, non-exported class declarations that implements the `RevHub`/`Serial` interface (and therefore doesn't need to duplicate its members), just so that TypeScript knows they're classes that we can instantiate.

`discoverRevHubs()` should also become a top-level function (probably better named `discoverRevHubAddresses()`).

**Comment by LandryNorris** [comment]
Implemented in #31
