### ISSUE TITLE
Fix issue where serial port often fails to open

### ISSUE THREAD

**Issue by NoahAndrews** [REVrobotics/node-rhsplib#26]
This code had to be written to work around that issue:
https://github.com/REVrobotics/first-global-2022/blob/8121ec3e846f1428cbea9f708a433dbb6595105b/field-controller/src/expansionHub.ts#L20-L36

**Comment by LandryNorris** [comment]
Error code is -102, which means [this line](https://github.com/REVrobotics/node-rhsplib/blob/16c50868a3e6858dc20948da5ad3964bfe33c881/RHSPlib/arch/win/RHSPlib_serial.c#L122) is running.

**Comment by LandryNorris** [comment]
It looks like the first time we call open, the actual name that makes it to C is often corrupted memory. The next time, it's valid.
