### ISSUE TITLE
Refactor `ExpansionHub.getDestAddress()` and `ExpansionHub.setDestAddress()` and methods that could be properties

### ISSUE THREAD

**Issue by NoahAndrews** [REVrobotics/node-rhsplib#44]
I think it makes the most sense to have operations that communicate with the hardware be explicit methods, while setting or getting things that only affect the library's state can be properties unless they are legitimately *doing* something, like `close()`. Typescript does support `get` and `set` functions for properties: https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters)

Additionally, "dest address" should be "module address".

Suggested changes:
* `isOpened()` -> `readonly isOpen`
* `getDestAddress()` -> `readonly moduleAddress`
* `setDestAddress()` -> removed, we already have `setNewModuleAddress()`
* `setResponseTimeoutMs()`/`getResponseTimeoutMs()` -> `responseTimeoutMs` (with a custom setter function)

**Comment by LandryNorris** [comment]
Will also remove unimplemented PWM methods
