### ISSUE TITLE
Standardize hardware for sample

### ISSUE THREAD

**Issue by LandryNorris** [REVrobotics/node-rhsplib#59]
As we add more features to the sample, we may want to describe hardware assumptions. Because this repo is public, anyone can view the sample and run it. If their hardware doesn't match what I'm working with now, some of these tasks won't run correctly. We should document expected hardware setup for each task.

**Comment by NoahAndrews** [comment]
I'd much rather have the sample not make any assumptions about what's connected to the Control or Expansion Hub. The servo command should require specifying which servo port, for example.

Ideally, this sample would be legitimately useful in its own right, for someone who just wants to make a motor move on their hub.
