### ISSUE TITLE
Sample: Allow user to optionally specify serial number and module address

### ISSUE THREAD

**Issue by NoahAndrews** [REVrobotics/node-rhsplib#66]
They should be able to specify neither, just one or the other, or both.

**Comment by LandryNorris** [comment]
How do we want the syntax of this to look? Right now, the overall structure is `sample command subcommand <param1> <param2> [optionalParam3] {flags}`, where we cannot have params between command and subcommand. Would flags be helpful here? Perhaps for example `sample digital read 1 -s "serial number" -a 2`?

**Comment by NoahAndrews** [comment]
Yep, flags.
