### ISSUE TITLE
Determine executable name

### ISSUE THREAD

**Issue by LandryNorris** [REVrobotics/node-rhsplib#67]
Currently, the sample module builds a main.js file that we can run via `node <path to dist>/main.js`. In the future, we may want to produce an executable (or just a better named js file), but we won't want it to be called 'main', and I'm not a fan of calling it 'sample' either. We should have a name indicating what it does.

**Comment by NoahAndrews** [comment]
I was literally thinking about this as I got ready this morning, lol

The `main.js` filename doesn't need to change, we just need to add a `bin` entry to its package.json: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin

I think the package name should be `rev-hub-cli`, and the command name should be `revhub`.
